### ISSUE TITLE
1958reposCavalier: Multi-value cell seems inconsistent with other datasets

### ISSUE THREAD

**Issue by andreabenedetti** [gustaveroudproject/geneticNetworksDataViz#1]
In the genetic dossier `1958reposCavalier` there seems to be an inconsistency with the other datasets, where an instance of a document has more than one id in `publicationIsReusedInDossierPart`. See the following extract from the JSON:

```
{
  "@id": "http://rdfh.ch/0112/B5vdBom5RPivCcfgn8GwRA",
  "@type": [
    "http://www.knora.org/ontology/0112/roud-oeuvres#PeriodicalArticle"
    ],
    "http://www.knora.org/ontology/0112/roud-oeuvres#isPublishedInPeriodical": [
      {
        "@value": "Papillons"
      }
    ],
    "http://www.knora.org/ontology/0112/roud-oeuvres#publicationHasDate": [
      {
        "@value": "1943-01-01 CE - 1943-12-31 CE"
      }
    ],
    "http://www.knora.org/ontology/0112/roud-oeuvres#publicationHasTitle": [
      {
        "@value": "Deux images de juin"
      }
    ],
    "http://www.knora.org/ontology/0112/roud-oeuvres#publicationIsReusedInDossierPart": [
      {
        "@id": "http://rdfh.ch/0112/reRnq2OoSVWuvfgA70yhxQ"
      },
      {
        "@id": "http://rdfh.ch/0112/I8LfBiT9Tqapf_uzQszWXA"
      }
  ]
},
```

This leads to blank rows when converting the JSON into a tabular form.

**Comment by elespdn** [comment]
Yes, the publication "Deux images de juin" is reused in two further publications: _Le repos du cavalier_ and _Air de la solitude_.

We can decide together what happens in this case (there are other cases like this in the corpus, not many, I would say less than 10)? The link to _Air de la solitude_ is not taken into account or it is shown as "something different"?

**Comment by elespdn** [comment]
See for example the genetic network of _Requiem_ in the drawing below. There is a grey link on the left, meaning that the article is reused outside the dossier of _Requiem_, for _Campagne perdue_ (another work by Roud).

![RequiemNetwork](https://user-images.githubusercontent.com/6794584/133434393-b5009031-4ccd-4fe6-bea7-5c401a6b3821.png)

**Comment by elespdn** [comment]
Actually it is a bit more complicated, because in the case of _Requiem_ above, one article is also reused outside the genetic network, in another article. While in the case of "Deux images de juin" first mentioned here, the link outside the genetic network would be not to a publication, but to a part of it.

So ... probably better to avoid this kind of links outside the genetic network, otherwise it becomes too complex.

What do you think, @andreabenedetti ? To be discussed in next meeting? I think we originally agreed upon "close" genetic networks, no link between them.
